<a href="https://colab.research.google.com/github/JarlynLoza/Actividad_7/blob/main/Actividad7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv('TrainingDataComplete.csv')
df.head(5)

,Id,Income,Age,Experience,Married/Single,House_Ownership,Car_Ownership,Profession,CITY,STATE,CURRENT_JOB_YRS,CURRENT_HOUSE_YRS,Risk_Flag
0,1,1303834,23,3,single,rented,no,Mechanical_engineer,Rewa,Madhya_Pradesh,3,13,0
1,2,7574516,40,10,single,rented,no,Software_Developer,Parbhani,Maharashtra,9,13,0
2,3,3991815,66,4,married,rented,no,Technical_writer,Alappuzha,Kerala,4,10,0
3,4,6256451,41,2,single,rented,yes,Software_Developer,Bhubaneswar,Odisha,2,12,1
4,5,5768871,47,11,single,rented,no,Civil_servant,Tiruchirappalli[10],Tamil_Nadu,3,14,1

##"Profession 1

In [ ]:
# Aplicar la condición y asignar etiquetas
base1=df[(df["Profession"]=="Mechanical_engineer") | (df["Profession"]=="Software_Developer")]
base1

,Id,Income,Age,Experience,Married/Single,House_Ownership,Car_Ownership,Profession,CITY,STATE,CURRENT_JOB_YRS,CURRENT_HOUSE_YRS,Risk_Flag
0,1,1303834,23,3,single,rented,no,Mechanical_engineer,Rewa,Madhya_Pradesh,3,13,0
1,2,7574516,40,10,single,rented,no,Software_Developer,Parbhani,Maharashtra,9,13,0
3,4,6256451,41,2,single,rented,yes,Software_Developer,Bhubaneswar,Odisha,2,12,1
25,26,1797876,76,20,single,norent_noown,no,Mechanical_engineer,Erode[17],Tamil_Nadu,11,14,0
56,57,5554586,39,18,single,rented,no,Software_Developer,Hindupur,Andhra_Pradesh,13,13,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
251919,251920,1356086,27,5,single,rented,yes,Software_Developer,Purnia[26],Bihar,5,14,1
251931,251932,9817339,64,11,single,rented,yes,Mechanical_engineer,Adoni,Andhra_Pradesh,11,14,0
251945,251946,1330670,73,10,single,rented,no,Software_Developer,Katihar,Bihar,10,11,0
251955,251956,1661386,38,17,single,rented,yes,Software_Developer,Jodhpur,Rajasthan,6,12,0
251956,251957,8914879,49,4,single,rented,no,Software_Developer,Durg,Chhattisgarh,4,13,0

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep=base1[['Income','Age','Experience']]
Var_Dep=base1['Profession']

X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=None)

#Se escalan todos los datos
escalar=StandardScaler()

#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de pruebla
X_train=escalar.fit_transform(X_train)
X_test=escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train,y_train)

#Realizamos una predicción
y_pred=algoritmo.predict(X_test)
y_pred


#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test,y_pred)
print('Matriz de confusión: ')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision=precision_score(y_test,y_pred,average="binary",pos_label="Mechanical_engineer")
print('Precisión del modelo: ')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test,y_pred)
print('Exactitud del modelo: ')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test,y_pred, average="binary",pos_label="Software_Developer")
print("Sensibiliad del modelo: ")
print(sensibilidad)

#El puntaje de F1 que es una combinación entre la precisión y la sensibilidad para esto importan
#Calculo el puntaje de F1 del modelo
from sklearn.metrics import f1_score
puntajef1=f1_score(y_test,y_pred,average="binary",pos_label="Software_Developer")
print("Puntaje F1 del modelo: ")
print(puntajef1)

Matriz de confusión:
[[1057  477]
 [ 895  652]]
Precisión del modelo:
0.5414959016393442
Exactitud del modelo:
0.5546900357026939
Sensibiliad del modelo:
0.42146089204912734
Puntaje F1 del modelo:
0.48729446935724957

##"Profession 2

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep=base1[['CURRENT_JOB_YRS','Age','Experience', 'CURRENT_HOUSE_YRS']]
Var_Dep=base1['Profession']

X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=None)

#Se escalan todos los datos
escalar=StandardScaler()

#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de pruebla
X_train=escalar.fit_transform(X_train)
X_test=escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train,y_train)

#Realizamos una predicción
y_pred=algoritmo.predict(X_test)
y_pred


#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test,y_pred)
print('Matriz de confusión: ')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision=precision_score(y_test,y_pred,average="binary",pos_label="Mechanical_engineer")
print('Precisión del modelo: ')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test,y_pred)
print('Exactitud del modelo: ')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test,y_pred, average="binary",pos_label="Software_Developer")
print("Sensibiliad del modelo: ")
print(sensibilidad)

#El puntaje de F1 que es una combinación entre la precisión y la sensibilidad para esto importan
#Calculo el puntaje de F1 del modelo
from sklearn.metrics import f1_score
puntajef1=f1_score(y_test,y_pred,average="binary",pos_label="Software_Developer")
print("Puntaje F1 del modelo: ")
print(puntajef1)

Matriz de confusión:
[[1037  494]
 [ 865  685]]
Precisión del modelo:
0.5452155625657203
Exactitud del modelo:
0.5589094449853943
Sensibiliad del modelo:
0.44193548387096776
Puntaje F1 del modelo:
0.5020153902528399

##"STATE" 1

In [ ]:
# Aplicar la condición y asignar etiquetas
base2=df[(df["STATE"]=="Andhra_Pradesh") | (df["STATE"]=="Maharashtra")]
base2

,Id,Income,Age,Experience,Married/Single,House_Ownership,Car_Ownership,Profession,CITY,STATE,CURRENT_JOB_YRS,CURRENT_HOUSE_YRS,Risk_Flag
1,2,7574516,40,10,single,rented,no,Software_Developer,Parbhani,Maharashtra,9,13,0
5,6,6915937,64,0,single,rented,no,Civil_servant,Jalgaon,Maharashtra,0,12,0
11,12,6623263,22,4,single,rented,no,Designer,Adoni,Andhra_Pradesh,4,14,0
15,16,5694236,39,2,married,rented,yes,Economist,Anantapuram[24],Andhra_Pradesh,2,10,0
17,18,3666346,56,12,single,rented,no,Politician,Bhusawal,Maharashtra,12,11,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
251983,251984,1759752,37,17,single,rented,no,Technical_writer,Ahmednagar,Maharashtra,14,13,0
251987,251988,6200535,72,6,single,rented,no,Physician,Sangli-Miraj_&_Kupwad,Maharashtra,6,12,0
251991,251992,6828311,36,11,single,owned,no,Designer,Nagpur,Maharashtra,11,13,0
251993,251994,8141027,60,10,single,rented,no,Secretary,Bhusawal,Maharashtra,9,13,1
251997,251998,4522448,46,7,single,rented,no,Design_Engineer,Kalyan-Dombivli,Maharashtra,7,12,0

In [ ]:
df1=df.groupby(['STATE'])['STATE'].count()
df1

STATE
Andhra_Pradesh       25297
Assam                 7062
Bihar                19780
Chandigarh             656
Chhattisgarh          3834
Delhi                 5490
Gujarat              11408
Haryana               7890
Himachal_Pradesh       833
Jammu_and_Kashmir     1780
Jharkhand             8965
Karnataka            11855
Kerala                5805
Madhya_Pradesh       14122
Maharashtra          25562
Manipur                849
Mizoram                849
Odisha                4658
Puducherry            1433
Punjab                4720
Rajasthan             9174
Sikkim                 608
Tamil_Nadu           16537
Telangana             7524
Tripura                809
Uttar_Pradesh        28400
Uttar_Pradesh[5]       743
Uttarakhand           1874
West_Bengal          23483
Name: STATE, dtype: int64

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep=base2[['Income','Experience']]
Var_Dep=base2['STATE']

X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=None)

#Se escalan todos los datos
escalar=StandardScaler()

#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de pruebla
X_train=escalar.fit_transform(X_train)
X_test=escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train,y_train)

#Realizamos una predicción
y_pred=algoritmo.predict(X_test)
y_pred


#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test,y_pred)
print('Matriz de confusión: ')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision=precision_score(y_test,y_pred,average="binary",pos_label="Andhra_Pradesh")
print('Precisión del modelo: ')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test,y_pred)
print('Exactitud del modelo: ')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test,y_pred, average="binary",pos_label="Maharashtra")
print("Sensibiliad del modelo: ")
print(sensibilidad)

#El puntaje de F1 que es una combinación entre la precisión y la sensibilidad para esto importan
#Calculo el puntaje de F1 del modelo
from sklearn.metrics import f1_score
puntajef1=f1_score(y_test,y_pred,average="binary",pos_label="Maharashtra")
print("Puntaje F1 del modelo: ")
print(puntajef1)

Matriz de confusión:
[[2729 4883]
 [2596 5050]]
Precisión del modelo:
0.5124882629107981
Exactitud del modelo:
0.5098309083759339
Sensibiliad del modelo:
0.6604760659168193
Puntaje F1 del modelo:
0.5745491779964732

##STATE 2

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep=base2[['Income','CURRENT_JOB_YRS', 'Age']]
Var_Dep=base2['STATE']

X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=None)

#Se escalan todos los datos
escalar=StandardScaler()

#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de pruebla
X_train=escalar.fit_transform(X_train)
X_test=escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train,y_train)

#Realizamos una predicción
y_pred=algoritmo.predict(X_test)
y_pred


#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test,y_pred)
print('Matriz de confusión: ')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision=precision_score(y_test,y_pred,average="binary",pos_label="Andhra_Pradesh")
print('Precisión del modelo: ')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test,y_pred)
print('Exactitud del modelo: ')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test,y_pred, average="binary",pos_label="Maharashtra")
print("Sensibiliad del modelo: ")
print(sensibilidad)

#El puntaje de F1 que es una combinación entre la precisión y la sensibilidad para esto importan
#Calculo el puntaje de F1 del modelo
from sklearn.metrics import f1_score
puntajef1=f1_score(y_test,y_pred,average="binary",pos_label="Maharashtra")
print("Puntaje F1 del modelo: ")
print(puntajef1)

Matriz de confusión:
[[3350 4250]
 [3105 4553]]
Precisión del modelo:
0.5189775367931836
Exactitud del modelo:
0.5179577926333726
Sensibiliad del modelo:
0.5945416557848002
Puntaje F1 del modelo:
0.5531863191786648

##'Income' 1

In [ ]:
# Aplicar la condición y asignar etiquetas
media_ingreso = df['Income'].mean()
print(media_ingreso)
df['Ingreso Alto/Bajo'] = df['Income'].apply(lambda x: 'Ingreso Alto' if x > media_ingreso else 'Ingreso Bajo')
df.head(5)

4997116.665325397

,Id,Income,Age,Experience,Married/Single,House_Ownership,Car_Ownership,Profession,CITY,STATE,CURRENT_JOB_YRS,CURRENT_HOUSE_YRS,Risk_Flag,Ingreso Alto/Bajo
0,1,1303834,23,3,single,rented,no,Mechanical_engineer,Rewa,Madhya_Pradesh,3,13,0,Ingreso Bajo
1,2,7574516,40,10,single,rented,no,Software_Developer,Parbhani,Maharashtra,9,13,0,Ingreso Alto
2,3,3991815,66,4,married,rented,no,Technical_writer,Alappuzha,Kerala,4,10,0,Ingreso Bajo
3,4,6256451,41,2,single,rented,yes,Software_Developer,Bhubaneswar,Odisha,2,12,1,Ingreso Alto
4,5,5768871,47,11,single,rented,no,Civil_servant,Tiruchirappalli[10],Tamil_Nadu,3,14,1,Ingreso Alto

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep=df[['Experience','Age']]
Var_Dep=df['Ingreso Alto/Bajo']

X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=None)

#Se escalan todos los datos
escalar=StandardScaler()

#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de pruebla
X_train=escalar.fit_transform(X_train)
X_test=escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train,y_train)

#Realizamos una predicción
y_pred=algoritmo.predict(X_test)
y_pred


#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test,y_pred)
print('Matriz de confusión: ')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision=precision_score(y_test,y_pred,average="binary",pos_label="Ingreso Bajo")
print('Precisión del modelo: ')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test,y_pred)
print('Exactitud del modelo: ')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test,y_pred, average="binary",pos_label="Ingreso Alto")
print("Sensibiliad del modelo: ")
print(sensibilidad)

#El puntaje de F1 que es una combinación entre la precisión y la sensibilidad para esto importan
#Calculo el puntaje de F1 del modelo
from sklearn.metrics import f1_score
puntajef1=f1_score(y_test,y_pred,average="binary",pos_label="Ingreso Bajo")
print("Puntaje F1 del modelo: ")
print(puntajef1)

Matriz de confusión:
[[21837 15818]
 [21798 16147]]
Precisión del modelo:
0.5051462537150008
Exactitud del modelo:
0.5024338624338625
Sensibiliad del modelo:
0.5799229849953526
Puntaje F1 del modelo:
0.4619367758546703

##INCOME 2

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep=df[['Experience','Age','CURRENT_JOB_YRS', 'CURRENT_HOUSE_YRS']]
Var_Dep=df['Ingreso Alto/Bajo']

X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=None)

#Se escalan todos los datos
escalar=StandardScaler()

#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de pruebla
X_train=escalar.fit_transform(X_train)
X_test=escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train,y_train)

#Realizamos una predicción
y_pred=algoritmo.predict(X_test)
y_pred


#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test,y_pred)
print('Matriz de confusión: ')
print(matriz)

#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision=precision_score(y_test,y_pred,average="binary",pos_label="Ingreso Bajo")
print('Precisión del modelo: ')
print(precision)

#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test,y_pred)
print('Exactitud del modelo: ')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test,y_pred, average="binary",pos_label="Ingreso Alto")
print("Sensibiliad del modelo: ")
print(sensibilidad)

#El puntaje de F1 que es una combinación entre la precisión y la sensibilidad para esto importan
#Calculo el puntaje de F1 del modelo
from sklearn.metrics import f1_score
puntajef1=f1_score(y_test,y_pred,average="binary",pos_label="Ingreso Bajo")
print("Puntaje F1 del modelo: ")
print(puntajef1)

Matriz de confusión:
[[21930 15772]
 [21552 16346]]
Precisión del modelo:
0.5089357992403014
Exactitud del modelo:
0.5062962962962962
Sensibiliad del modelo:
0.5816667550793061
Puntaje F1 del modelo:
0.46692184643510054

In [ ]:
df.head()

,Id,Income,Age,Experience,Married/Single,House_Ownership,Car_Ownership,Profession,CITY,STATE,CURRENT_JOB_YRS,CURRENT_HOUSE_YRS,Risk_Flag,Ingreso Alto/Bajo
0,1,1303834,23,3,single,rented,no,Mechanical_engineer,Rewa,Madhya_Pradesh,3,13,0,Ingreso Bajo
1,2,7574516,40,10,single,rented,no,Software_Developer,Parbhani,Maharashtra,9,13,0,Ingreso Alto
2,3,3991815,66,4,married,rented,no,Technical_writer,Alappuzha,Kerala,4,10,0,Ingreso Bajo
3,4,6256451,41,2,single,rented,yes,Software_Developer,Bhubaneswar,Odisha,2,12,1,Ingreso Alto
4,5,5768871,47,11,single,rented,no,Civil_servant,Tiruchirappalli[10],Tamil_Nadu,3,14,1,Ingreso Alto

#Experience 1

In [ ]:
media = df['Experience'].mean()

#Dividir la columna en dos basándonos en la mediana
df['Experience'] = df['Experience'].apply(lambda x: 'exp_alta' if x > media else 'exp_baja')
df

,Id,Income,Age,Experience,Married/Single,House_Ownership,Car_Ownership,Profession,CITY,STATE,CURRENT_JOB_YRS,CURRENT_HOUSE_YRS,Risk_Flag,Ingreso Alto/Bajo
0,1,1303834,23,exp_baja,single,rented,no,Mechanical_engineer,Rewa,Madhya_Pradesh,3,13,0,Ingreso Bajo
1,2,7574516,40,exp_baja,single,rented,no,Software_Developer,Parbhani,Maharashtra,9,13,0,Ingreso Alto
2,3,3991815,66,exp_baja,married,rented,no,Technical_writer,Alappuzha,Kerala,4,10,0,Ingreso Bajo
3,4,6256451,41,exp_baja,single,rented,yes,Software_Developer,Bhubaneswar,Odisha,2,12,1,Ingreso Alto
4,5,5768871,47,exp_alta,single,rented,no,Civil_servant,Tiruchirappalli[10],Tamil_Nadu,3,14,1,Ingreso Alto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251995,251996,8154883,43,exp_alta,single,rented,no,Surgeon,Kolkata,West_Bengal,6,11,0,Ingreso Alto
251996,251997,2843572,26,exp_baja,single,rented,no,Army_officer,Rewa,Madhya_Pradesh,6,11,0,Ingreso Bajo
251997,251998,4522448,46,exp_baja,single,rented,no,Design_Engineer,Kalyan-Dombivli,Maharashtra,7,12,0,Ingreso Bajo
251998,251999,6507128,45,exp_baja,single,rented,no,Graphic_Designer,Pondicherry,Puducherry,0,10,0,Ingreso Alto
251999,252000,9070230,70,exp_alta,single,rented,no,Statistician,Avadi,Tamil_Nadu,7,11,0,Ingreso Alto

In [ ]:
df1=df.groupby(['Experience'])['Experience'].count()
df1

Experience
exp_alta    120799
exp_baja    131201
Name: Experience, dtype: int64

In [ ]:
#Reemplazar 'exp_alta' por 1 y 'exp_baja' por 0 en la columna 'experience'
df['Experience'] = df['Experience'].replace({'exp_alta': 1, 'exp_baja': 0}).astype(float)
df

,Id,Income,Age,Experience,Married/Single,House_Ownership,Car_Ownership,Profession,CITY,STATE,CURRENT_JOB_YRS,CURRENT_HOUSE_YRS,Risk_Flag,Ingreso Alto/Bajo
0,1,1303834,23,0.0,single,rented,no,Mechanical_engineer,Rewa,Madhya_Pradesh,3,13,0,Ingreso Bajo
1,2,7574516,40,0.0,single,rented,no,Software_Developer,Parbhani,Maharashtra,9,13,0,Ingreso Alto
2,3,3991815,66,0.0,married,rented,no,Technical_writer,Alappuzha,Kerala,4,10,0,Ingreso Bajo
3,4,6256451,41,0.0,single,rented,yes,Software_Developer,Bhubaneswar,Odisha,2,12,1,Ingreso Alto
4,5,5768871,47,1.0,single,rented,no,Civil_servant,Tiruchirappalli[10],Tamil_Nadu,3,14,1,Ingreso Alto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251995,251996,8154883,43,1.0,single,rented,no,Surgeon,Kolkata,West_Bengal,6,11,0,Ingreso Alto
251996,251997,2843572,26,0.0,single,rented,no,Army_officer,Rewa,Madhya_Pradesh,6,11,0,Ingreso Bajo
251997,251998,4522448,46,0.0,single,rented,no,Design_Engineer,Kalyan-Dombivli,Maharashtra,7,12,0,Ingreso Bajo
251998,251999,6507128,45,0.0,single,rented,no,Graphic_Designer,Pondicherry,Puducherry,0,10,0,Ingreso Alto
251999,252000,9070230,70,1.0,single,rented,no,Statistician,Avadi,Tamil_Nadu,7,11,0,Ingreso Alto

In [ ]:
#Declaramos las variables dependientes e independientes para regresion logistica
vars_indep = df[['Risk_Flag','Age', 'Income', 'CURRENT_HOUSE_YRS']] #Numéricas
var_dep = df['Experience'] #Dicotomicas

In [ ]:
#Redefinimos las variables
X= vars_indep
y= var_dep

In [ ]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
#Se escalan todos los datos
escalar = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#Definimos el algoritmo a utilizar
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[36923  2625]
 [33331  2721]]

In [ ]:
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="binary", pos_label=0)
print('Precisión del modelo:')
print(precision)

print('\t')


#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

print('\t')

#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print('Sensibilidad del modelo:')
print(sensibilidad)

print('\t')

#el puntaje F1 que es una combinación entre la precisión y la sensibilidad, para esto importamos f1_score.
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="binary", pos_label=0)
print('Puntaje F1 del modelo:')
print(puntajef1)

Precisión del modelo:
0.5255643806758334

Exactitud del modelo:
0.5243915343915344

Sensibilidad del modelo:
0.07547431487850882

Puntaje F1 del modelo:
0.6725378408407862

#Experience 2

In [ ]:
#Declaramos las variables dependientes e independientes para regresion logistica
vars_indep = df[['Age', 'Income', 'CURRENT_HOUSE_YRS']] #Numéricas
var_dep = df['Experience'] #Dicotomicas

In [ ]:
#Redefinimos las variables
X= vars_indep
y= var_dep

In [ ]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
#Se escalan todos los datos
escalar = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#Definimos el algoritmo a utilizar
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[38109  1144]
 [35130  1217]]

In [ ]:
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="binary", pos_label=0)
print('Precisión del modelo:')
print(precision)

print('\t')

#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

print('\t')

#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print('Sensibilidad del modelo:')
print(sensibilidad)

print('\t')

#el puntaje F1 que es una combinación entre la precisión y la sensibilidad, para esto importamos f1_score.
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="binary", pos_label=1)
print('Puntaje F1 del modelo:')
print(puntajef1)

Precisión del modelo:
0.5203375250890919

Exactitud del modelo:
0.5201851851851852

Sensibilidad del modelo:
0.03348281838941316

Puntaje F1 del modelo:
0.06288105817918777

#'Age' 1

In [ ]:
media = df['Age'].mean()

#Dividir la columna en dos basándonos en la mediana
df['Age'] = df['Age'].apply(lambda x: 'altos' if x > media else 'bajos')
df

,Id,Income,Age,Experience,Married/Single,House_Ownership,Car_Ownership,Profession,CITY,STATE,CURRENT_JOB_YRS,CURRENT_HOUSE_YRS,Risk_Flag,Ingreso Alto/Bajo
0,1,1303834,bajos,0.0,single,rented,no,Mechanical_engineer,Rewa,Madhya_Pradesh,3,13,0,Ingreso Bajo
1,2,7574516,bajos,0.0,single,rented,no,Software_Developer,Parbhani,Maharashtra,9,13,0,Ingreso Alto
2,3,3991815,altos,0.0,married,rented,no,Technical_writer,Alappuzha,Kerala,4,10,0,Ingreso Bajo
3,4,6256451,bajos,0.0,single,rented,yes,Software_Developer,Bhubaneswar,Odisha,2,12,1,Ingreso Alto
4,5,5768871,bajos,1.0,single,rented,no,Civil_servant,Tiruchirappalli[10],Tamil_Nadu,3,14,1,Ingreso Alto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251995,251996,8154883,bajos,1.0,single,rented,no,Surgeon,Kolkata,West_Bengal,6,11,0,Ingreso Alto
251996,251997,2843572,bajos,0.0,single,rented,no,Army_officer,Rewa,Madhya_Pradesh,6,11,0,Ingreso Bajo
251997,251998,4522448,bajos,0.0,single,rented,no,Design_Engineer,Kalyan-Dombivli,Maharashtra,7,12,0,Ingreso Bajo
251998,251999,6507128,bajos,0.0,single,rented,no,Graphic_Designer,Pondicherry,Puducherry,0,10,0,Ingreso Alto
251999,252000,9070230,altos,1.0,single,rented,no,Statistician,Avadi,Tamil_Nadu,7,11,0,Ingreso Alto

In [ ]:
#Reemplazar 'exp_alta' por 1 y 'exp_baja' por 0 en la columna 'experience'
df['Age'] = df['Age'].replace({'altos': 1, 'bajos': 0}).astype(float)
df

,Id,Income,Age,Experience,Married/Single,House_Ownership,Car_Ownership,Profession,CITY,STATE,CURRENT_JOB_YRS,CURRENT_HOUSE_YRS,Risk_Flag,Ingreso Alto/Bajo
0,1,1303834,0.0,0.0,single,rented,no,Mechanical_engineer,Rewa,Madhya_Pradesh,3,13,0,Ingreso Bajo
1,2,7574516,0.0,0.0,single,rented,no,Software_Developer,Parbhani,Maharashtra,9,13,0,Ingreso Alto
2,3,3991815,1.0,0.0,married,rented,no,Technical_writer,Alappuzha,Kerala,4,10,0,Ingreso Bajo
3,4,6256451,0.0,0.0,single,rented,yes,Software_Developer,Bhubaneswar,Odisha,2,12,1,Ingreso Alto
4,5,5768871,0.0,1.0,single,rented,no,Civil_servant,Tiruchirappalli[10],Tamil_Nadu,3,14,1,Ingreso Alto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251995,251996,8154883,0.0,1.0,single,rented,no,Surgeon,Kolkata,West_Bengal,6,11,0,Ingreso Alto
251996,251997,2843572,0.0,0.0,single,rented,no,Army_officer,Rewa,Madhya_Pradesh,6,11,0,Ingreso Bajo
251997,251998,4522448,0.0,0.0,single,rented,no,Design_Engineer,Kalyan-Dombivli,Maharashtra,7,12,0,Ingreso Bajo
251998,251999,6507128,0.0,0.0,single,rented,no,Graphic_Designer,Pondicherry,Puducherry,0,10,0,Ingreso Alto
251999,252000,9070230,1.0,1.0,single,rented,no,Statistician,Avadi,Tamil_Nadu,7,11,0,Ingreso Alto

In [ ]:
#Declaramos las variables dependientes e independientes para regresion logistica
vars_indep = df[['Risk_Flag','Experience', 'Income', 'CURRENT_HOUSE_YRS']] #Numéricas
var_dep = df['Age'] #Dicotomicas

In [ ]:
X=Vars_Indep
y=Var_Dep

In [ ]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
#Se escalan todos los datos
escalar = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#Definimos el algoritmo a utilizar
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['Ingreso Alto', 'Ingreso Bajo', 'Ingreso Bajo', ...,
       'Ingreso Alto', 'Ingreso Alto', 'Ingreso Alto'], dtype=object)